---
- hosts: web
  become: yes
  remote_user: ubuntu
  tasks:
    - name: php repo
      apt_repository:
        repo: ppa:ondrej/php
    - name: apt update
      apt:
        update_cache: yes
    - name: apt update all
      apt:
        upgrade: dist
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    - name: install requirements
      apt:
        pkg:
        - mariadb-client
        - apache2
        - php
